version: "3.8"

services:
  web:
    build: .
    container_name: movie_app
    ports:
      - "5000:5000"
    environment:
      NEO4J_URI: bolt://host.docker.internal:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: neo4j_password
      MONGO_URL: mongodb://host.docker.internal:27017/
    extra_hosts:
      - "host.docker.internal:host-gateway"
